name: Run Rector and Cache
description: Caches Rector results and runs Rector on the project
inputs:
  skip-rector:
    description: 'Skip Rector setup and processing'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Cache Rector
      uses: actions/cache@v4
      with:
        path: .rector
        key: rector-cache-${{ runner.os }}-${{ github.run_id }}
        restore-keys: rector-cache-${{ runner.os }}-

    - name: Create Rector cache directory
      run: mkdir -p .rector
      shell: bash

    - name: Run Rector
      if: ${{ inputs.skip-rector == 'false' }}
      run: php vendor/bin/rector process --config=rector.php
      shell: bash
