name: "code-formatter"
on:
  workflow_call:
    inputs:
      skip-npm:
        description: 'Whether to skip installing NPM dependencies'
        default: false
        type: boolean

jobs:
  code-formatter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.3"]
    steps:
      - name: PHP Setup
        uses: jcergolj/reusable-github-actions/.github/actions/php-setup@master
        with:
          php-version: ${{ matrix.php }}

      - name: Composer
        uses: jcergolj/reusable-github-actions/.github/actions/composer-setup@master

      - name: NPM
        uses: jcergolj/reusable-github-actions/.github/actions/npm-setup@master
        with:
          skip-npm: ${{ inputs.skip-npm }}

      - name: Run Prettier - format js files
        if: ${{ inputs.skip-npm == false }}
        run: npm run format-js

      - name: Run Prettier - format blade files
        if: ${{ inputs.skip-npm == false }}
        run: npm run format-blade

      - name: Run Rector
        uses: jcergolj/reusable-github-actions/.github/actions/rector@master

      - name: Run Laravel Pint
        run: vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: code auto-format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
