name: "deploy"
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/jcergolj/staging.issuefy.dev
          git fetch
          git reset --hard origin/master
          git pull

          composer install --no-interaction --prefer-dist --optimize-autoloader

          ( flock -w 10 9 || exit 1
              echo 'Restarting FPM...'; sudo -S service php8.3-fpm reload ) 9>/tmp/fpmlock

          if [ -f artisan ]; then
              php artisan migrate --force
          fi

          php artisan optimize
