name: "deploy"
on:
  push:
    branches:
      - master
  workflow_call:
    secrets:
      DEPLOY_SSH_PRIVATE_KEY:
        description: "Private SSH key for the production deployer user"
        required: true
      PAT_TOKEN:
        description: "GitHub token used by secret scanning workflows"
        required: true

jobs:
  tests:
    uses: jcergolj/reusable-github-actions/.github/workflows/tests.yml@master
    secrets: inherit

  phpstan:
    uses: jcergolj/reusable-github-actions/.github/workflows/larastan.yml@master
    secrets: inherit

  pint:
    uses: jcergolj/reusable-github-actions/.github/workflows/pint.yml@master

  rector:
    uses: jcergolj/reusable-github-actions/.github/workflows/rector.yml@master

  envy:
    uses: jcergolj/reusable-github-actions/.github/workflows/envy.yml@master
    secrets: inherit

  gitleaks:
    uses: jcergolj/reusable-github-actions/.github/workflows/gitleaks.yml@master
    secrets: inherit

  trufflehog:
    uses: jcergolj/reusable-github-actions/.github/workflows/trufflehog-scan.yml@master
    secrets: inherit

  deploy:
    needs:
      - tests
      - phpstan
      - pint
      - rector
      - envy
      - gitleaks
      - trufflehog
    uses: jcergolj/reusable-github-actions/.github/workflows/deploy-only.yml@master
    secrets: inherit
