name: phpinsights
on:
  workflow_call:

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.3"]
    steps:
      - name: PHP Setup
        uses: jcergolj/reusable-github-actions/.github/actions/php-setup@master
        with:
          php-version: ${{ matrix.php }}

      - name: Composer
        uses: jcergolj/reusable-github-actions/.github/actions/composer-setup@master

      - name: Run insights
        run: php artisan insights --no-interaction --no-interaction --fix -v
