name: "trufflehog scan"
on:
  workflow_call:  # If this is a reusable workflow, keep this, otherwise replace with something like push or pull_request triggers.

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TruffleHog via curl
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Run TruffleHog to Scan Last Commit
        run: |
          trufflehog git https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --branch ${{ github.ref_name }} --fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
